### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by torvh** [moom825/xeno-rat#10]
hello, i build rat, open it in my computer and fully working. but if i open it on any else computer/virtual machine this not working, program is autostarting but i dont have computer on list can you help me fix this my discord: veiss._

**Comment by moom825** [comment]
you can message me on discord, my username is moom825, the issue you are having is most likely due to the fact you didnt port forward (meaning computers outside of your network cant contact you)

**Comment by torvh** [comment]
> you can message me on discord, my username is moom825, the issue you are having is most likely due to the fact you didnt port forward (meaning computers outside of your network cant contact you)

added you bro
