### ISSUE TITLE
This is amazing 

### ISSUE THREAD

**Issue by HD7K** [moom825/xeno-rat#11]
This is an amazing malware project keep on working on it please. Though I think hvnc needs a little more work and the info stealer doesn't work I was testing it on a vm but the info stealer might need to add more support of different browsers.
If I had to say anything must be added is probably a crypt to make this malware fud as of rn the virus total is 27/72 and this amazing as a free GitHub rat but I feel like if u made a priv rat this would be fixed id definitely pay for a priv version of this rat
But anyway amazing project would love to see this more updated way better than any other GitHub rat

**Comment by HD7K** [comment]
I was using the default edge it doesn't bother me but check ur ideas page I would absolutely buy a private rat from you or crypter

**Comment by moom825** [comment]
sorry but I dont (and dont plan to) sell a private version, and making and
up keeping a crypter is a lot of work I dont have time for sadly
