### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by chikabou** [moom825/xeno-rat#15]
i finish built and the executable is ready but when someone open it nothing shows up .
juste when i open it on my local it shows the 127.0.0.1 ip and i can use the tool .
can you help so when i send it to my friend it works.

**Comment by chikabou** [comment]
thank you but it is not a antivirus problem because my friend stopped his antivirus but im not sure about the ip should i use my public ip ? and should i have an open port to connect with my friend computer ?

**Comment by chikabou** [comment]
i use my public ip address and port 4444 even in my router settings i put my ip and the port 4444 open that means it must work i think but it didn't . valus3000 please if you can help this is my discord : najed2.0

**Comment by chikabou** [comment]
thank you very much . the problem is that i was using my public ip on my router settings .
thank you .

**Comment by NFS11** [comment]
hi all, what if your router settings show something like this?
![Screenshot_20241102_194958_Chrome](https://github.com/user-attachments/assets/8e0de93b-0257-41c0-ad47-6a422f8f273e)

**Comment by NFS11** [comment]
also with the protocol should I be good to go? and idk what to do with the external and internal ports do I just set them all to something like e.g 4444? and for ip address do I need to do anything about that or no. sorry if I'm disturbing.

**Comment by zamora1221** [comment]
> hi all, what if your router settings show something like this? ![Screenshot_20241102_194958_Chrome](https://private-user-images.githubusercontent.com/176389798/382503050-8e0de93b-0257-41c0-ad47-6a422f8f273e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMzA1MDksIm5iZiI6MTczMjMzMDIwOSwicGF0aCI6Ii8xNzYzODk3OTgvMzgyNTAzMDUwLThlMGRlOTNiLTAyNTctNDFjMC1hZDQ3LTZhNDIyZjhmMjczZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QwMjUwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzA3MzkwZTk1ZWUzMDZkMWFiOWYyZWRhOGY4ODViNWZhZDM3OGJmYTIxYTFmMzFlY2E1ZDk5MmI1Zjg5NmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SrYdZCcwoANxjfCT-bu_yAp3xbAA-tgZslN4Oeyr7kg)

were you able to figure it out? i have the same thing

**Comment by NFS11** [comment]
@zamora1221 apparantly if youre using one port (e.g 4111 or something) you gotta set everything to 4111. you also have to make sure the ip setting in the builder is set to what is shown in ipconfig command in cmd. however when i had tried this and checked it using canyouseeme.org , it didnt find the open port despite my setting in router being right. even upon changing the wf.msc settings. if i may ask, are you using the same router as me?

**Comment by Valus3000** [comment]
@zamora1221 
@NFS11 

External ports and internal ports would be the same for both start and end. Whatever port you use to make your payload e.g 4111. Also canyouseeme is a waste of time. Do not use. You seem to be following the instructions I post correctly. However, I assume you making a mistake along the way. Double check method just to be sure. 

Things to double check / try / note
1. The payload ip used and router ip opened are two different things. NOT the same
2. Rem you cannot use the same payload on the same computer, if using, then use ip 127.0.0.1 to test the software
3. If using windows firewall and you did not allow the software to gain access, then do that.
4. Disable firewall just in case, if issue persist
5. Ensure you assign and open the port in the software itself, so it may listen
6. Ensure PASSWORD are the same in software as the payload

**Comment by NFS11** [comment]
@Valus3000  how do I check if the port forwarding worked? when running on my own pc I did use the default ip so it worked but I have some questions:
1. what do I enter for the ip address? do I execute ipconfig command in cmd and use the ip shown there?
2. how do I check if it worked?
3. can my router or isp affect the connection or port forwarding?
4. what about double nat? apparantly that can affect the port forwarding so can i fix that?

thanks for the tips I just want to make sure if this is in order.

**Comment by NFS11** [comment]
also has anyone managed to fix the issue where even when setting port forwarding rule and inbound rule in wf.msc the port is still not found

**Comment by Valus3000** [comment]
> also has anyone managed to fix the issue where even when setting port forwarding rule and inbound rule in wf.msc the port is still not found

@NFS11 

I have no issue what-so-ever. Therefore issue is on your side, either router/firewall/or something you doing wrong unfortunately.

**As to your previous questions:**

1. You use your ip address you **see online** for the payload and your pc ip address in **ipconfig** to open the port. I recommend you look into ddns or domain or rdp, rather than using your ip address. If you just testing or ip is static then this should not be an issue, so disregard.
2. It will work when you did everything correctly and got connection. This is the only way to know, unless you use a listening program for your ports or use netstat -ab or -aon commands. Yet this will only say that the port is open. 
3. Yes, hence the reason you trying to open a port because of NAT/firewall on most modern routers. ISP even sometime blocks port from opening even though router says it's open.
4. Double NAT is hell on earth. But you can open ports normally like any other router but it is a big hassle. So either open port on MAIN router to Second router then Second router to your pc OR just disable second router. The latter being the easiest of them all, as you basically disable double nat. 

Hope this helps man, peace.

**Comment by NFS11** [comment]
@Valus3000 thanks you are a life saver. i am not sure if my isp is blocking my port but i am using ports that aren't 4444 or 4782 and other commonly used ports. im not exactly sure if its double nat but apparantly it may be a problem according to other users that use my isp. i will try to use an rdp if i can get it working. thank you for your help, we need more people like you

also wanted to ask: can i just use a vpn as an alternative? apparantly i can do that after some quick googling

**Comment by Valus3000** [comment]
> @Valus3000 thanks you are a life saver. i am not sure if my isp is blocking my port but i am using ports that aren't 4444 or 4782 and other commonly used ports. im not exactly sure if its double nat but apparantly it may be a problem according to other users that use my isp. i will try to use an rdp if i can get it working. thank you for your help, we need more people like you
> 
> also wanted to ask: can i just use a vpn as an alternative? apparantly i can do that after some quick googling

@NFS11
You can, but you need a vpn with port forwarding which I think most vpn do not offer. As it is seen/flagged as malware and illegal usage. If I was you, I would use a free ddns for now, just to test.
