### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Valus3000** [moom825/xeno-rat#17]
1. Can you provide an option to use pastebin(or another/multiple services of choice) to **_update ip/host or domain on the client side._** 
Therefore you cannot lose the rat as you can easily change pastebin ip/host to point to your new ip address. Would even be better if you allow pastebin login to get raw files that are set to private, therefore ip not expose. This would be an amazing feature.

2. Another feature would be to allow us to update the client **_remotely_** with ease when you release new features and bug fixes.

Everything else is absolutely great. I am really impress with the Hnvc, it works great.

**Comment by moom825** [comment]
both of those things are added to the list thx
