### ISSUE TITLE
Most options not working on hvnc

### ISSUE THREAD

**Issue by Amittere1** [moom825/xeno-rat#19]
Hi again when I use hvnc on most clients the only options that work are chrome, run, cmd, and powershell, the rest such as edge and explorer when i try it does nothing just a black screen. The only time edge worked was when i tested it on my other PC

**Comment by moom825** [comment]
yea currently looking into both issues, the explorer one is because its running it as admin which causes some issues, working on a fix. and for the edge, I got no clue, but I'm looking into it.

**Comment by moom825** [comment]
still looking into the edge problem, but for the explorer issue, there is now an option called de-escalate to user, explorer has some issue launching as admin
