### ISSUE TITLE
The victims don't disappear, they don't connect

### ISSUE THREAD

**Issue by Akylloficial** [moom825/xeno-rat#2]
![Sem títul2323o](https://github.com/moom825/xeno-rat/assets/148152626/f033bb27-d74c-41b8-aa43-07a2f52b5061)

Can someone help me?

**Comment by moom825** [comment]
sorry could you explain your issue a bit? (like the relvence of that screenshot, and explain the issue some more)

**Comment by Akylloficial** [comment]
I made the virus, sent it to the victim and it still didn't connect. I tried everything but I couldn't

**Comment by moom825** [comment]
its most likely a port forwarding issue, would you be able to message me? (moom825 on telegram and discord)

**Comment by Akylloficial** [comment]
ok

**Comment by moom825** [comment]
solved, they didnt enable the port in the listener 👍
