### ISSUE TITLE
How to get this up and running

### ISSUE THREAD

**Issue by SlushPuppyCodingHole** [moom825/xeno-rat#24]
I'm kinda new to rats, last time I used them was in 2019 and when I used cracked nanocore and port forwarded apparently the Russian government connected to my RAT, so I'm kinda always scared of doing port forwarding. Anyway I've tried looking everywhere for how to get a RAT up and running and Ive seen so many things like buy an RDP port or use a VPS to do it and I really have no idea what any of that means, basically what i'm saying is whats the easiest way to get this up and running securely?

**Comment by 0rb5** [comment]
How about you actually learn how all of this works instead of just focusing on the Rat
