### ISSUE TITLE
Use folders my man

### ISSUE THREAD

**Issue by DanielSparta** [moom825/xeno-rat#27]
Use folders and put inside them the classes, Your project will look alot better.
For example take a look at my RAT project that I'm currently working on:
https://github.com/DanielSparta/2024-RAT-projet
alot more beutiful when you have folder called "Socket" that have things like accept, create.. Or when you  have folder for the client that have class send, receive.... or Tools folder for all the tools, setup folder for all the things such as persistence... GUI folder for GUI's...

Think about It :)

**Comment by DanielSparta** [comment]
Also, I can see that every class you have, have too many "garbage" code, make your project more clearly and simple to read.
**If you will have specific Folders for every thing, and class for every topic, your project can be alot better!**

For example, look at my client side RAT:
https://github.com/DanielSparta/2024-RAT-projet/tree/main/Desktop%20Control%20panel/RATserverSparta

Looks so good..

**Comment by moom825** [comment]
tbh, idc, its my coding style and makes it eaiser for me to read, i dont want to switch through 50 different files just to change one thing. have fun and gl with your project.

**Comment by DanielSparta** [comment]
> tbh, idc, its my coding style and makes it eaiser for me to read, i dont want to switch through 50 different files just to change one thing. have fun and gl with your project.

I see there are alot script kiddies on your project, "Valus3000" :/ well, thats a RAT after all.
Anyways, your visual studio as IDE? I think its alot more easy to read when you just double clicking
well thanks I will keep working on my project, just think about that.. folders and more classes..

**Comment by moom825** [comment]
for me when i have a structured layout in my mind its just easier. well
everything is eaiser when you know where things are. its just a personal
preference, and this isnt some super high tier project, its just my
learning project. I do understand what you mean, having a nice oraganized
way of doing things is always nice, especially if you want a new person to
look at it and understand it. but this project is mainly just for me, its
just a learning project.
