### ISSUE TITLE
A função HVNC não esta funcionando como deveria. Esta funcionando ao contrario.

### ISSUE THREAD

**Issue by mrlonmra** [moom825/xeno-rat#3]
A função HVNC não esta funcionando como deveria. Esta funcionando ao contrario.

**Comment by moom825** [comment]
hey sorry, i dont really speak spanish but google translate tells me the hvnc is not working for you? are you able to go into further detail, like what you see, if it crashs, etc. whats makes you say it doesnt work.

**Comment by mrlonmra** [comment]
HVNC does not display DESKTOP, although other commands work like powershell, edge, etc. But I don't have Desktop visibility, is this normal or could it be a bug? Thank you in advance! Peace and light.
Sorry friend, by the way, it's Portuguese, not Spanish.
![Captura de tela 2023-10-29 111250](https://github.com/moom825/xeno-rat/assets/26064875/e48cf46d-56ce-4f73-aab0-3db5f108d129)

**Comment by moom825** [comment]
hey there, I am so sorry for language mix up.

In order to start the desktop in the hvnc you need to click the explorer button (the default desktop in windows explorer). did you do that?

**Comment by mrlonmra** [comment]
Thanks for the clarification, my friend!

**Comment by mrlonmra** [comment]
Sometimes it works, and other times it opens Explorer on the client. But anyway, thank you!

**Comment by moom825** [comment]
that is strange, I've never experienced that issue, can I ask what version of windows is being used, or any other useful info?

**Comment by EG1116AM** [comment]
on windows 10, sometime when click on Open Explorer it's show desktop, some time it's open explorer windows. but it's not problem.

have problem: on Desktop, click on browser, I can select profile but cant type anything on Address Bar. it's aloways show Restore Button but cant click.

work normal with EDGE, Chrome button at bottom on hvnc window

Thanks Sir for your code.
