### ISSUE TITLE
HVNC Browsers

### ISSUE THREAD

**Issue by matmad** [moom825/xeno-rat#34]
Hi, some stuff regarding HVNC
HVNC starts all borwsers and explorer on teh client machine instaed of in HVNC window, Chrome is the only one that works perfectly fine even with profile cloning on. CMD and Powershell does not start neither in HVNC window nor on client machine.

Source code compiled with VS Community 2022 Version 17.8.1. Both client and server Win 10 x64 machines.

BTW
Thank you for the source code - this rat is really great!

**Comment by matmad** [comment]
Sorry - update: cmd and powershell started correctly in hvnc window, just with some inhumane delay :)

**Comment by LightYagami28** [comment]
Close the issues
