### ISSUE TITLE
How to write a new plugin?

### ISSUE THREAD

**Issue by badboycxcc** [moom825/xeno-rat#37]
How to write a new plugin? For example, a pop-up window?

**Comment by moom825** [comment]
you want to follow the flow of the other plugins, you can just copy paste some of the plugins code and edit it to do the popup. 
it should compile to a dll, I would suggest changing the build path (you can see what a good build path would be by looking the build path of the other plugins).

In the server look in the mainform.cs and just follow the control flow of how the plugins are loaded and run.

that should be about it, if you have any specific questions about the plugin creation or having issues with it feel free to msg me 👍

**Comment by badboycxcc** [comment]
Is dll a reflective dll?

**Comment by moom825** [comment]
it is loaded in reflectivly

**Comment by badboycxcc** [comment]
ok
