### ISSUE TITLE
Cpl instead of dll?

### ISSUE THREAD

**Issue by SantaLaMuerte** [moom825/xeno-rat#49]
Can tool use cpl instead of dlls? cpl can be added to exclusions without wd warnings. And sometimes dll uploading is broken cause some windows defending features , even with system/admin rights on machine.  
Thanks for tool - work nice!

**Comment by moom825** [comment]
im not exactly sure how that would work, do you have some example?

**Comment by SantaLaMuerte** [comment]
Closing, bad idea. Every (90%) cpl files outside now is marking suspicious - so not big profit 
but i was mean something like that https://github.com/chango77747/PowerShellCplLoader. Cause in some cases dll loading blocking by some secure mechanisms of Windows
