### ISSUE TITLE
!!Complete Breakdown of all Tools!! Thanks in Advanced.

### ISSUE THREAD

**Issue by R3d-Developer** [moom825/xeno-rat#86]
So i have been playing around with this beatiful toy here... and after working on a bit of batch magic just like simple stuff to trick my "friend" (with consent of course) into executing the file without it being detected or atleast if i would use it which i wont but:

it broke or more specifically all the plugins when trying to do anything with or without admin privilages it tells me "Error blabla.dll"
the blabla being the certain tool i try to use, i tried reinstalling, Rebuilding a new rat, tried to restart the computer (couldve worked dont know :8) and all that but it doesent seem to work anymore and im just out of ideas... anybody know what the problem may be? 

It just happend so out of the nothing

Thanks in advanced!

**Comment by R3d-Developer** [comment]
![image](https://github.com/user-attachments/assets/8f930614-c7ac-482f-bac3-cbc25d6e2b27)
![image](https://github.com/user-attachments/assets/6ef4ad8b-ccfa-46fc-a2bf-89d85054a977)
Translation: (( This File or Assembly "170408 bytes loaded from Xeno rat client, [...] ))
(btw its a diffrent byte number depending on which tool i try to use e.g. Microphone would be 505856 or ProcessManager 17408...)

FIXED: Seems like the DLL files got blocked by the Windows AV which is weird it didnt do that before but ey it works now

**Comment by NFS11** [comment]
@R3d-Developer lol when that error goes off its like 99% of the time the av. sp far, my only solution is to either use a script to disable defender or use hvnc to your advantage to disable defender. anyway i gotta appreciate your breakdown!
